### ISSUE TITLE
Merubah form pendaftaran

### ISSUE THREAD

**Issue by nd3w** [drajathasan/member_self_registration#2]
File apa yang harus saya edit kalau saya ingin menambah info berupa paragraf di form pendaftaran (URL: /index.php?p=daftar_online ) contohnya di baris sebelum tombol submit. Saya coba merubah file daftar_online.inc.php karena sepertinya di file ini form dibuat, tapi  tidak ada perubahan yang terjadi.

**Comment by drajathasan** [comment]
Perubahan apa yang dilakukan? Skrip apa yang ditambahkan?

**Comment by nd3w** [comment]
Saya ingin menambahkan info berupa paragraf pada form pendaftaran.
Gambar: https://prnt.sc/Aw_W6XMKEC2Z

Yang sudah saya lakukan adalah dengan edit file daftar_online.inc.php dengan menambah 1 baris kode sesudah baris nomor 89:

    createAnything('', '<p>Silakan menghubungi pustakawan/wati kami pada nomor 086221122 untuk aktivasi keanggotaan Anda.</p>');

Tapi tidak ada perubahan yang terjadi.

**Comment by drajathasan** [comment]
Kalau sekadar notifikasi kan bisa pakai yang ada digambar berikut:

klik tombol hijau
![image](https://user-images.githubusercontent.com/38057222/200568171-f139337b-ac62-4c3e-80d5-9b6ede59acd9.png)

Tinggal diisi aja dibagian paling bawah.
![image](https://user-images.githubusercontent.com/38057222/200568497-be708185-aa39-4966-b522-39fd63b28fb7.png)

**Comment by nd3w** [comment]
Kalau notifikasi sudah dilakukan. Inginnya menambah langsung di form, supaya langsung kelihatan dan calon anggota sempat mencatatnya terlebih dulu.

**Comment by drajathasan** [comment]
jangan pakai createAnything, karena itu akan membuat isian form. tinggal pake skrip 

`echo '<p>Silakan menghubungi pustakawan/wati kami pada nomor 086221122 untuk aktivasi keanggotaan Anda.</p>';`

taruh dimana anda mau letakan.

Saya close issue ini.
