### ISSUE TITLE
Form not appearing

### ISSUE THREAD

**Issue by phaseism** [drajathasan/member_self_registration#3]
After activating on admin side, p=daftar_online still showing 
 error 'Folder C:\slims9\httpd\htdocs\bulian\plugins\member_self_registration\bs4formmaker.inc.php tidak ada. Pastikan folder itu tersedia.' 
Is there something else I'm supposed to do?

**Comment by drajathasan** [comment]
Please rename current folder name of that plugin to member_self_registration in plugins folder.

**Comment by phaseism** [comment]
Thank you!

**Comment by arifardia** [comment]
> Please rename current folder name of that plugin to member_self_registration in plugins folder.

setelah mengganti nama folder masih muncul error yang sama bg
